// Auto-generated types from AgentMark
// Do not edit this file directly

interface SupportAgent$SupportAgentIn {
  /**
   * The customer's support question.
   */
  question: string;
  /**
   * The product the customer is asking about.
   */
  product: string;
}


type SupportAgent$SupportAgentOut = string

type SupportAgent$SupportAgent = {
  kind: 'text';
  input:  SupportAgent$SupportAgentIn;
  output: SupportAgent$SupportAgentOut;
};

export default interface AgentmarkTypes {
  "support-agent/support-agent.prompt.mdx": SupportAgent$SupportAgent,
  "support-agent/support-agent.prompt": SupportAgent$SupportAgent,
  "support-agent/support-agent": SupportAgent$SupportAgent
}
