// Auto-generated types from AgentMark
// Do not edit this file directly

interface CustomerSupportIn {
  /**
   * The customer's name
   */
  customer_name?: string;
  /**
   * The customer's support request
   */
  message: string;
}


type CustomerSupportOut = string

type CustomerSupport = {
  kind: 'text';
  input:  CustomerSupportIn;
  output: CustomerSupportOut;
};

export default interface AgentmarkTypes {
  "customer-support.prompt.mdx": CustomerSupport,
  "customer-support.prompt": CustomerSupport,
  "customer-support": CustomerSupport
}
